### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by slZheng077** [impel-intelligence/dippy-bittensor-subnet#10]
I have already submitted my role-playing model to the Hugging Face repository, but I haven't received any rewards or feedback tao. How can I troubleshoot this issue, or where can I check the status of my submission?

**Comment by donaldknoller** [comment]
see https://github.com/impel-intelligence/dippy-bittensor-subnet/blob/main/docs/FAQ.md#my-model-has-a-high-score-but-im-not-receiving-enough-emissions-why
