### ISSUE TITLE
No module named "docker" during local evaluation

### ISSUE THREAD

**Issue by itorgov** [impel-intelligence/dippy-bittensor-subnet#107]
When I try to run the local evaluation script I get the following error:

```
user@07af7ec5-8fe0-46d8-8622-d86be9b45149:~/dippy-bittensor-subnet$ python dippy_validation_api/evaluator.py --image grader:latest --repo_namespace tistak --repo_name 7cnzdjpB1HTKAjXbnRE9 --chat_template_type chatml --hash 12060815441122160010
Traceback (most recent call last):
  File "/home/user/dippy-bittensor-subnet/dippy_validation_api/evaluator.py", line 7, in <module>
    import docker
ModuleNotFoundError: No module named 'docker'
```

To fix this error the `docker` package has to be added to the `requirements.eval.txt` file.

**Comment by donaldknoller** [comment]
The `requirements.eval.txt` is only meant to be installed _inside_ the docker container for evaluation. For running the evaluator script, the appropriate set of requirements is actually `requirements.api.txt`
