### ISSUE TITLE
dippyai wandb page not publicly accessible

### ISSUE THREAD

**Issue by samtensora** [impel-intelligence/dippy-bittensor-subnet#45]
This section on [setting up wandb](https://github.com/impel-intelligence/dippy-bittensor-subnet/blob/main/README.md#setup-wandb-highly-recommended---validators-please-read) points to a "publicly accessible page. [here](https://wandb.ai/dippyai/).".

Is it publicly accessable?

<img width="1345" alt="Screenshot 2024-08-20 at 17 41 55" src="https://github.com/user-attachments/assets/1d556d20-6ad0-4255-932f-5a6ac023e181">

**Comment by donaldknoller** [comment]
it is publicly visible if you navigate to "projects"

**Comment by samtensora** [comment]
Thanks, should we update the URL to something like this (i.e. hoping it takes ppl straight to a projects page)?

https://wandb.ai/dippyai/dippy-prod
