### ISSUE TITLE
ADMIN_KEY and DIPPY_KEY not documented in README

### ISSUE THREAD

**Issue by samtensora** [impel-intelligence/dippy-bittensor-subnet#46]
ADMIN_KEY and DIPPY_KEY are required to run [start_validation_service.sh](https://github.com/impel-intelligence/dippy-bittensor-subnet/blob/main/dippy_validation_api/start_validation_service.sh) but are not documented in the README.md

What are they for and where are they from?

**Comment by donaldknoller** [comment]
They are custom values as can be seen in the code

**Comment by samtensora** [comment]
Should we document them in the README.md?

**Comment by samtensora** [comment]
For example this PR https://github.com/impel-intelligence/dippy-bittensor-subnet/pull/50
