### ISSUE TITLE
issues with running local evaluation API

### ISSUE THREAD

**Issue by samtensora** [impel-intelligence/dippy-bittensor-subnet#51]
There are multiple issues with [running the local evaluation API](https://github.com/impel-intelligence/dippy-bittensor-subnet?tab=readme-ov-file#running-the-model-evaluation-api-optional). I am opening this thread to hopefully get the local evaluation API working for everyone. I am here to help so lmk if you would like me to submit PRs or break out the comments below into separate issues...

(1) [test_api.py](https://github.com/impel-intelligence/dippy-bittensor-subnet/blob/main/dippy_validation_api/test_api.py) requires `python-dotenv` and `supabase`. Should they be added to requirements_val_api.txt?

(2) [Supabase](https://supabase.com/) seems to require
- docker
- docker compose
- postgres
- relevant configurations

and this ^ is quite a lot to set up (would make for a long README.md and would be error prone). Should we provide a Dockerfile and instructions on how to use it?

(3) test_api.py and start_validation_service.sh are expecting a .env file in the root directory of the repo, for example to set [ADMIN_KEY and DIPPY_KEY](https://github.com/impel-intelligence/dippy-bittensor-subnet/pull/50/commits/2d7b4f4546d29e526ab839001cb335b6aaaf0f22)

(4) [start_validation_service.sh](https://github.com/impel-intelligence/dippy-bittensor-subnet/blob/main/dippy_validation_api/start_validation_service.sh) seems to also (indirectly) expects other environment variables in that root level .env (e.g. HF_ACCESS_TOKEN, SUPABASE_..). 

(5) [start_validation_service.sh](https://github.com/impel-intelligence/dippy-bittensor-subnet/blob/main/dippy_validation_api/start_validation_service.sh) **silently fails** when these ^ environment variables are missing because [validation_api.py sends stdout and sterr directly to the log file](https://github.com/impel-intelligence/dippy-bittensor-subnet/blob/8218a09271f2a9621d8fea38f591cc3000ff4955/dippy_validation_api/start_validation_service.sh#L87) which is located in the relative path `api_logs/validation_api.log`.

(6) [start_validation_service.sh](https://github.com/impel-intelligence/dippy-bittensor-subnet/blob/main/dippy_validation_api/start_validation_service.sh) can silently fail and then **falsely declare** that..

```
Starting validation_api...
All APIs are running in the background
```
Should we check the API is running between these two statements? Possibly something like this

```
# Start the validation_api
echo "Starting validation_api..."
./../$VENV_NAME/bin/python3 validation_api.py --queues 1 --main-api-port $VALIDATION_API_PORT >> "api_logs/validation_api.log" 2>&1 &
api_pid=$!
echo $api_pid > api_logs/validation_api.pid

# Wait for a short period to see if the process fails
sleep 5

# Check if the process is still running
if ! ps -p $api_pid > /dev/null; then
    echo "Failed to start validation_api. Check api_logs/validation_api.log for details."
    exit 1
fi

echo "All APIs are running in the background"
```

**Comment by donaldknoller** [comment]
As mentioned in the notes, the validation api is currently undergoing a rehaul and is not expected to be locally runnable at this time
